import type { NotificationTypeDefinition } from '@open-mercato/shared/modules/notifications/types'

export const TAXI_FLEET_TRIP_ORDER_NOTIFY_FEATURE = 'taxi_fleet.trip.order.notify'
export const TAXI_FLEET_TRIP_PAID_NOTIFY_FEATURE = 'taxi_fleet.trip.paid.notify'
export const TAXI_FLEET_TRIP_CONFIRMED_NOTIFY_FEATURE = 'taxi_fleet.trip.confirmed.notify'
export const TAXI_FLEET_TRIP_CANCELLED_NOTIFY_FEATURE = 'taxi_fleet.trip.cancelled.notify'
export const TAXI_FLEET_FINANCIAL_INCOME_NOTIFY_FEATURE = 'taxi_fleet.financial.income.notify'
export const TAXI_FLEET_FINANCIAL_EXPENSE_NOTIFY_FEATURE = 'taxi_fleet.financial.expense.notify'
export const TAXI_FLEET_TRIP_SUBMITTED_NOTIFY_FEATURE = 'taxi_fleet.trip.submitted.notify'
export const TAXI_FLEET_SETTLEMENT_SUBMITTED_NOTIFY_FEATURE = 'taxi_fleet.settlement.submitted.notify'
export const TAXI_FLEET_PLATFORM_SYNC_NOTIFY_FEATURE = 'taxi_fleet.platform_sync.notify'

const tripViewAction = {
  id: 'view',
  labelKey: 'common.view',
  variant: 'outline' as const,
  href: '/backend/taxi-fleet/trips/{sourceEntityId}',
  icon: 'external-link',
}

const monthlySettlementDriverViewAction = {
  id: 'view',
  labelKey: 'common.view',
  variant: 'outline' as const,
  href: '/driver/monthly-settlements/{sourceEntityId}',
  icon: 'external-link',
}

export const notificationTypes: NotificationTypeDefinition[] = [
  {
    type: 'taxi_fleet.trip.order_created',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_order_created.title',
    bodyKey: 'taxi_fleet.notifications.trip_order_created.body',
    icon: 'car',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_order_created',
      scopeFeature: 'taxi_fleet.manage_trips',
      lockFeature: TAXI_FLEET_TRIP_ORDER_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.assigned',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_assigned.title',
    bodyKey: 'taxi_fleet.notifications.trip_assigned.body',
    icon: 'user-check',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_assigned',
      scopeFeature: 'taxi_fleet.view',
      audience: 'individual',
      pushChannel: { locked: true, defaultEnabled: true },
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.reminder',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_reminder.title',
    bodyKey: 'taxi_fleet.notifications.trip_reminder.body',
    icon: 'clock',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_reminder',
      scopeFeature: 'taxi_fleet.driver',
      audience: 'individual',
      defaultEnabled: false,
      pushChannel: { locked: true, defaultEnabled: true },
    },
    actions: [],
    linkHref: '/driver/trips/{sourceEntityId}',
    expiresAfterHours: 24,
  },
  {
    type: 'taxi_fleet.week_end.reminder',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.week_end_reminder.title',
    bodyKey: 'taxi_fleet.notifications.week_end_reminder.body',
    icon: 'calendar',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.week_end_reminder',
      scopeFeature: 'taxi_fleet.driver',
      audience: 'individual',
      defaultEnabled: false,
      pushChannel: { locked: true, defaultEnabled: true },
    },
    actions: [],
    expiresAfterHours: 24,
  },
  {
    type: 'taxi_fleet.assignment.planned',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.assignment_planned.title',
    bodyKey: 'taxi_fleet.notifications.assignment_planned.body',
    icon: 'calendar',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.assignment_planned',
      scopeFeature: 'taxi_fleet.driver',
      audience: 'individual',
      pushChannel: { defaultEnabled: true },
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline' as const,
        href: '/driver/assignments',
        icon: 'external-link',
      },
    ],
    linkHref: '/driver/assignments',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.driver_broadcast',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.driver_broadcast.title',
    bodyKey: 'taxi_fleet.notifications.driver_broadcast.body',
    icon: 'megaphone',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.driver_broadcast',
      scopeFeature: 'taxi_fleet.driver',
      audience: 'individual',
      pushChannel: { defaultEnabled: true },
    },
    actions: [],
    expiresAfterHours: 336,
  },
  {
    type: 'taxi_fleet.trip.paid',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_paid.title',
    bodyKey: 'taxi_fleet.notifications.trip_paid.body',
    icon: 'credit-card',
    severity: 'success',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_paid',
      scopeFeature: 'taxi_fleet.manage_trips',
      lockFeature: TAXI_FLEET_TRIP_PAID_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.confirmed',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_confirmed.title',
    bodyKey: 'taxi_fleet.notifications.trip_confirmed.body',
    icon: 'badge-check',
    severity: 'success',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_confirmed',
      scopeFeature: 'taxi_fleet.manage_trips',
      lockFeature: TAXI_FLEET_TRIP_CONFIRMED_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.cancelled',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_cancelled.title',
    bodyKey: 'taxi_fleet.notifications.trip_cancelled.body',
    icon: 'ban',
    severity: 'warning',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_cancelled',
      scopeFeature: 'taxi_fleet.manage_trips',
      lockFeature: TAXI_FLEET_TRIP_CANCELLED_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.financial_entry.income_created',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.financial_income_created.title',
    bodyKey: 'taxi_fleet.notifications.financial_income_created.body',
    icon: 'receipt',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.financial_income_created',
      scopeFeature: 'taxi_fleet.manage_settlements',
      lockFeature: TAXI_FLEET_FINANCIAL_INCOME_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline',
        href: '/backend/taxi-fleet/drivers/{driverProfileId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/taxi-fleet/drivers/{driverProfileId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.financial_entry.expense_created',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.financial_expense_created.title',
    bodyKey: 'taxi_fleet.notifications.financial_expense_created.body',
    icon: 'wallet',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.financial_expense_created',
      scopeFeature: 'taxi_fleet.manage_settlements',
      lockFeature: TAXI_FLEET_FINANCIAL_EXPENSE_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline',
        href: '/backend/taxi-fleet/drivers/{driverProfileId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/taxi-fleet/drivers/{driverProfileId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.settlement.ready',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.settlement_ready.title',
    bodyKey: 'taxi_fleet.notifications.settlement_ready.body',
    icon: 'wallet',
    severity: 'success',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.settlement_ready',
      scopeFeature: 'taxi_fleet.view',
      audience: 'individual',
      pushChannel: { defaultEnabled: true },
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline' as const,
        href: '/driver/settlements/{sourceEntityId}',
        icon: 'external-link',
      },
    ],
    linkHref: '/driver/settlements/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.monthly_settlement.ready',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.monthly_settlement_ready.title',
    bodyKey: 'taxi_fleet.notifications.monthly_settlement_ready.body',
    icon: 'wallet',
    severity: 'success',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.monthly_settlement_ready',
      scopeFeature: 'taxi_fleet.view',
      audience: 'individual',
      pushChannel: { defaultEnabled: true },
    },
    actions: [monthlySettlementDriverViewAction],
    linkHref: '/driver/monthly-settlements/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.submitted',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_submitted.title',
    bodyKey: 'taxi_fleet.notifications.trip_submitted.body',
    icon: 'car',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_submitted',
      scopeFeature: 'taxi_fleet.manage_trips',
      lockFeature: TAXI_FLEET_TRIP_SUBMITTED_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.trip.pending_authorization',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.trip_pending_authorization.title',
    bodyKey: 'taxi_fleet.notifications.trip_pending_authorization.body',
    icon: 'shield-check',
    severity: 'warning',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.trip_pending_authorization',
      scopeFeature: 'taxi_fleet.trips.authorize_internal',
    },
    actions: [tripViewAction],
    linkHref: '/backend/taxi-fleet/trips/{sourceEntityId}',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.settlement.submitted',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.settlement_submitted.title',
    bodyKey: 'taxi_fleet.notifications.settlement_submitted.body',
    icon: 'wallet',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.settlement_submitted',
      scopeFeature: 'taxi_fleet.manage_settlements',
      lockFeature: TAXI_FLEET_SETTLEMENT_SUBMITTED_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline',
        href: '/backend/taxi-fleet/settlements',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/taxi-fleet/settlements',
    expiresAfterHours: 168,
  },
  {
    type: 'taxi_fleet.platform_sync.completed',
    module: 'taxi_fleet',
    titleKey: 'taxi_fleet.notifications.platform_sync_completed.title',
    bodyKey: 'taxi_fleet.notifications.platform_sync_completed.body',
    icon: 'upload',
    severity: 'info',
    userPreference: {
      labelKey: 'taxi_fleet.notifications.preferences.platform_sync_completed',
      scopeFeature: 'taxi_fleet.manage_platform_sync',
      lockFeature: TAXI_FLEET_PLATFORM_SYNC_NOTIFY_FEATURE,
      lockedWhenRoleGrants: true,
    },
    actions: [
      {
        id: 'view',
        labelKey: 'common.view',
        variant: 'outline',
        href: '/backend/taxi-fleet/trips',
        icon: 'external-link',
      },
    ],
    linkHref: '/backend/taxi-fleet/trips',
    expiresAfterHours: 72,
  },
]

export default notificationTypes
