import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

const mailDeliveryBootstrapPlugin: GeneratorPlugin = {
  id: 'mail_delivery.notification-strategy',
  conventionFile: 'mail-delivery.bootstrap.ts',
  importPrefix: 'MAIL_DELIVERY_BOOTSTRAP',
  configExpr: () => 'null',
  outputFileName: 'mail-delivery-bootstrap.generated.ts',
  buildOutput: ({ importSection, entriesLiteral }) => `// AUTO-GENERATED by mercato generate registry
${importSection ? `${importSection}\n` : ''}export const mailDeliveryBootstrapEntries = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`,
  bootstrapRegistration: {
    entriesExportName: 'mailDeliveryBootstrapEntries',
    registrationImports: [
      `import { registerNodemailerNotificationDeliveryStrategy } from '@/modules/mail_delivery/lib/nodemailerNotificationDelivery'`,
    ],
    buildCall: () => 'registerNodemailerNotificationDeliveryStrategy()',
  },
}

export const generatorPlugins = [mailDeliveryBootstrapPlugin]
