import {
  buildTripRouteNotes,
  composeTripNotes,
  defaultTripRequestDetails,
  stripAutoGeneratedTripNotes,
} from '../tripRequestForm'

describe('stripAutoGeneratedTripNotes', () => {
  it('removes repeated Trasa summary blocks and keeps manual notes', () => {
    const notes = [
      'Trasa: A → B\nDystans: 15 km\nPasażerowie: 3\nPłatność: PayPal',
      'Trasa: A → B\nDystans: 15 km\nPasażerowie: 3\nPłatność: PayPal',
      'Trasa: A → B\nBagaż podręczny: 3\nNumer lotu: FR 1234\nPłatność: PayPal',
      'Proszę zadzwonić 10 min wcześniej',
    ].join('\n\n')

    expect(stripAutoGeneratedTripNotes(notes)).toBe('Proszę zadzwonić 10 min wcześniej')
  })
})

describe('composeTripNotes', () => {
  it('writes a single summary even when previous auto notes are present', () => {
    const details = {
      ...defaultTripRequestDetails(),
      fromAddress: 'KRK',
      toAddress: 'Prażmowskiego',
      distanceKm: '15',
      durationText: '16 min',
      passengers: '3',
      handLuggage: '3',
      holdLuggage: '2',
      flightNumber: 'FR 1234',
      isAirportPickup: true,
      serviceType: 'airport' as const,
      paymentType: 'electronic' as const,
    }
    const previous = [
      buildTripRouteNotes(details),
      buildTripRouteNotes(details),
      'Notatka operatora',
    ].join('\n\n')

    const composed = composeTripNotes(details, previous)
    expect(composed?.split('\n\n')).toHaveLength(2)
    expect(composed).toContain('Trasa: KRK → Prażmowskiego')
    expect(composed).toContain('Numer lotu: FR 1234')
    expect(composed).toContain('Notatka operatora')
    expect(composed?.match(/Trasa:/g)).toHaveLength(1)
  })
})
