// Auto-registered field components loaded at runtime.
// This file can be regenerated by module generators. Keep imports side-effectful.
import '@open-mercato/core/modules/attachments/fields/attachment'
import '@open-mercato/core/modules/dictionaries/fields/dictionary'
import '@open-mercato/core/modules/entities/fields/color'
import '@open-mercato/core/modules/entities/fields/icon'

export function loadAll() {
  // No-op: imports above perform registration via side effects
}
